add hw2 and change project
yalof/react-demo pull request #1
Opened 2022-04-22 13:22 UTC by yalof

2022-04-22 13:47 UTC, vl-domorad requested changes

2022-04-22 13:47 UTC, vl-domorad commented on src/components/CardPost/CardPost.tsx
> +import '../../components/CardPost/CardPost.css';
можно заменить на ./CardPost.css

2022-04-22 13:47 UTC, vl-domorad commented on src/pages/Registration/Registration.tsx
> +    <Button className='login-title_Registration' btnText='Registration'/>
Повторение кода и немного неправильный подход изначально, основное в задании было менять содержимое на странице при нажатии на кнопки login и registration, а не менять сами страницы местами.
Т. е. архитектура должна быть такой:
Кнопки Login Redgistration -> onClick => setActiveTab(tabName)
activeTab === 'login' ? :

2022-04-25 22:49 UTC, yalof commented on src/components/CardPost/CardPost.tsx
> +import '../../components/CardPost/CardPost.css';
Исправлено, изменила название файлов. Поэтому это изменение теперь в ./Posts.tsx

2022-04-29 07:03 UTC, vl-domorad commented
Можешь мержить

2022-04-29 09:55 UTC, merged